import logging
from sqlalchemy.orm import Session

from ..models import Connector, Station

logger = logging.getLogger(__name__)

MOCK_STATIONS = [
    {
        "ocm_id": 100001,
        "name": "ChargeFox - Sydney CBD",
        "address": "1 Martin Place",
        "suburb": "Sydney",
        "state": "NSW",
        "postcode": "2000",
        "country": "Australia",
        "latitude": -33.8682,
        "longitude": 151.2113,
        "operator_name": "ChargeFox",
        "usage_type": "Public",
        "usage_cost": "$0.35/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 4},
        ],
    },
    {
        "ocm_id": 100002,
        "name": "Tesla Supercharger - St Leonards",
        "address": "2 Frederick St",
        "suburb": "St Leonards",
        "state": "NSW",
        "postcode": "2065",
        "country": "Australia",
        "latitude": -33.8235,
        "longitude": 151.1980,
        "operator_name": "Tesla",
        "usage_type": "Public",
        "usage_cost": "$0.52/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 250, "voltage": 400, "amperage": 625, "quantity": 6},
        ],
    },
    {
        "ocm_id": 100003,
        "name": "Evie Network - Chatswood",
        "address": "1 Anderson St",
        "suburb": "Chatswood",
        "state": "NSW",
        "postcode": "2067",
        "country": "Australia",
        "latitude": -33.7966,
        "longitude": 151.1839,
        "operator_name": "Evie Networks",
        "usage_type": "Public",
        "usage_cost": "$0.40/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 350, "voltage": 800, "amperage": 500, "quantity": 3},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 1},
        ],
    },
    {
        "ocm_id": 100004,
        "name": "JOLT - North Sydney",
        "address": "100 Miller St",
        "suburb": "North Sydney",
        "state": "NSW",
        "postcode": "2060",
        "country": "Australia",
        "latitude": -33.8361,
        "longitude": 151.2064,
        "operator_name": "JOLT",
        "usage_type": "Public",
        "usage_cost": "Free first 7kWh/day, then $0.35/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "Type 2 (Socket)", "power_kw": 7, "voltage": 240, "amperage": 32, "quantity": 4},
        ],
    },
    {
        "ocm_id": 100005,
        "name": "BP Pulse - Parramatta",
        "address": "159 Church St",
        "suburb": "Parramatta",
        "state": "NSW",
        "postcode": "2150",
        "country": "Australia",
        "latitude": -33.8162,
        "longitude": 151.0020,
        "operator_name": "BP Pulse",
        "usage_type": "Public",
        "usage_cost": "$0.45/kWh",
        "is_24hr": 0,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 150, "voltage": 400, "amperage": 375, "quantity": 2},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 1},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 2},
        ],
    },
    {
        "ocm_id": 100006,
        "name": "AmpCharge - Surry Hills",
        "address": "425 Elizabeth St",
        "suburb": "Surry Hills",
        "state": "NSW",
        "postcode": "2010",
        "country": "Australia",
        "latitude": -33.8853,
        "longitude": 151.2076,
        "operator_name": "AmpCharge",
        "usage_type": "Public",
        "usage_cost": "$0.38/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 75, "voltage": 400, "amperage": 200, "quantity": 2},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 2},
        ],
    },
    {
        "ocm_id": 100007,
        "name": "Tesla Destination - Bondi Junction",
        "address": "500 Oxford St",
        "suburb": "Bondi Junction",
        "state": "NSW",
        "postcode": "2022",
        "country": "Australia",
        "latitude": -33.8926,
        "longitude": 151.2484,
        "operator_name": "Tesla",
        "usage_type": "Public",
        "usage_cost": "$0.30/kWh",
        "is_24hr": 0,
        "status_type": "Operational",
        "connectors": [
            {"type": "Type 2 (Tethered)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 4},
        ],
    },
    {
        "ocm_id": 100008,
        "name": "ChargeFox - Alexandria",
        "address": "75 Bourke Rd",
        "suburb": "Alexandria",
        "state": "NSW",
        "postcode": "2015",
        "country": "Australia",
        "latitude": -33.9116,
        "longitude": 151.1961,
        "operator_name": "ChargeFox",
        "usage_type": "Public",
        "usage_cost": "$0.35/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 2},
        ],
    },
    {
        "ocm_id": 100009,
        "name": "Evie Network - Hornsby",
        "address": "236 Pacific Hwy",
        "suburb": "Hornsby",
        "state": "NSW",
        "postcode": "2077",
        "country": "Australia",
        "latitude": -33.7022,
        "longitude": 151.0991,
        "operator_name": "Evie Networks",
        "usage_type": "Public",
        "usage_cost": "$0.42/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 350, "voltage": 800, "amperage": 500, "quantity": 2},
        ],
    },
    {
        "ocm_id": 100010,
        "name": "NRMA - Newtown",
        "address": "240 King St",
        "suburb": "Newtown",
        "state": "NSW",
        "postcode": "2042",
        "country": "Australia",
        "latitude": -33.8944,
        "longitude": 151.1790,
        "operator_name": "NRMA",
        "usage_type": "Public",
        "usage_cost": "$0.30/kWh members, $0.50/kWh guests",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 1},
        ],
    },
    {
        "ocm_id": 100011,
        "name": "ChargeFox - Melbourne CBD",
        "address": "25 Collins St",
        "suburb": "Melbourne",
        "state": "VIC",
        "postcode": "3000",
        "country": "Australia",
        "latitude": -37.8167,
        "longitude": 144.9692,
        "operator_name": "ChargeFox",
        "usage_type": "Public",
        "usage_cost": "$0.35/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 4},
        ],
    },
    {
        "ocm_id": 100012,
        "name": "Tesla Supercharger - Richmond VIC",
        "address": "100 Bridge Rd",
        "suburb": "Richmond",
        "state": "VIC",
        "postcode": "3121",
        "country": "Australia",
        "latitude": -37.8186,
        "longitude": 144.9984,
        "operator_name": "Tesla",
        "usage_type": "Public",
        "usage_cost": "$0.52/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 250, "voltage": 400, "amperage": 625, "quantity": 8},
        ],
    },
    {
        "ocm_id": 100013,
        "name": "Evie Network - Southbank VIC",
        "address": "3 Southbank Blvd",
        "suburb": "Southbank",
        "state": "VIC",
        "postcode": "3006",
        "country": "Australia",
        "latitude": -37.8228,
        "longitude": 144.9664,
        "operator_name": "Evie Networks",
        "usage_type": "Public",
        "usage_cost": "$0.40/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 350, "voltage": 800, "amperage": 500, "quantity": 4},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
        ],
    },
    {
        "ocm_id": 100014,
        "name": "JOLT - Fitzroy",
        "address": "200 Brunswick St",
        "suburb": "Fitzroy",
        "state": "VIC",
        "postcode": "3065",
        "country": "Australia",
        "latitude": -37.7992,
        "longitude": 144.9776,
        "operator_name": "JOLT",
        "usage_type": "Public",
        "usage_cost": "Free first 7kWh/day, then $0.35/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "Type 2 (Socket)", "power_kw": 7, "voltage": 240, "amperage": 32, "quantity": 6},
        ],
    },
    {
        "ocm_id": 100015,
        "name": "BP Pulse - St Kilda",
        "address": "10 Fitzroy St",
        "suburb": "St Kilda",
        "state": "VIC",
        "postcode": "3182",
        "country": "Australia",
        "latitude": -37.8624,
        "longitude": 144.9805,
        "operator_name": "BP Pulse",
        "usage_type": "Public",
        "usage_cost": "$0.45/kWh",
        "is_24hr": 0,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 150, "voltage": 400, "amperage": 375, "quantity": 2},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 2},
        ],
    },
    {
        "ocm_id": 100016,
        "name": "AmpCharge - Parramatta",
        "address": "60 George St",
        "suburb": "Parramatta",
        "state": "NSW",
        "postcode": "2150",
        "country": "Australia",
        "latitude": -33.8111,
        "longitude": 151.0068,
        "operator_name": "AmpCharge",
        "usage_type": "Public",
        "usage_cost": "$0.38/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 75, "voltage": 400, "amperage": 200, "quantity": 2},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 1},
        ],
    },
    {
        "ocm_id": 100017,
        "name": "NRMA - Gosford",
        "address": "1 Mann St",
        "suburb": "Gosford",
        "state": "NSW",
        "postcode": "2250",
        "country": "Australia",
        "latitude": -33.4254,
        "longitude": 151.3415,
        "operator_name": "NRMA",
        "usage_type": "Public",
        "usage_cost": "$0.30/kWh members, $0.50/kWh guests",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 1},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 2},
        ],
    },
    {
        "ocm_id": 100018,
        "name": "ChargeFox - Wollongong",
        "address": "84 Crown St",
        "suburb": "Wollongong",
        "state": "NSW",
        "postcode": "2500",
        "country": "Australia",
        "latitude": -34.4251,
        "longitude": 150.8933,
        "operator_name": "ChargeFox",
        "usage_type": "Public",
        "usage_cost": "$0.35/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 2},
        ],
    },
    {
        "ocm_id": 100019,
        "name": "Evie Network - Newcastle",
        "address": "400 Hunter St",
        "suburb": "Newcastle",
        "state": "NSW",
        "postcode": "2300",
        "country": "Australia",
        "latitude": -32.9276,
        "longitude": 151.7779,
        "operator_name": "Evie Networks",
        "usage_type": "Public",
        "usage_cost": "$0.42/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 350, "voltage": 800, "amperage": 500, "quantity": 2},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 1},
        ],
    },
    {
        "ocm_id": 100020,
        "name": "Tesla Supercharger - Penrith",
        "address": "545 High St",
        "suburb": "Penrith",
        "state": "NSW",
        "postcode": "2750",
        "country": "Australia",
        "latitude": -33.7540,
        "longitude": 150.6980,
        "operator_name": "Tesla",
        "usage_type": "Public",
        "usage_cost": "$0.52/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 250, "voltage": 400, "amperage": 625, "quantity": 4},
        ],
    },
    {
        "ocm_id": 100021,
        "name": "ChargeFox - Brisbane CBD",
        "address": "200 Queen St",
        "suburb": "Brisbane City",
        "state": "QLD",
        "postcode": "4000",
        "country": "Australia",
        "latitude": -27.4698,
        "longitude": 153.0251,
        "operator_name": "ChargeFox",
        "usage_type": "Public",
        "usage_cost": "$0.35/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 2},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 4},
        ],
    },
    {
        "ocm_id": 100022,
        "name": "Tesla Supercharger - Fortitude Valley",
        "address": "100 Ann St",
        "suburb": "Fortitude Valley",
        "state": "QLD",
        "postcode": "4006",
        "country": "Australia",
        "latitude": -27.4568,
        "longitude": 153.0354,
        "operator_name": "Tesla",
        "usage_type": "Public",
        "usage_cost": "$0.52/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 250, "voltage": 400, "amperage": 625, "quantity": 8},
        ],
    },
    {
        "ocm_id": 100023,
        "name": "Evie Network - South Brisbane",
        "address": "30 Stanley St",
        "suburb": "South Brisbane",
        "state": "QLD",
        "postcode": "4101",
        "country": "Australia",
        "latitude": -27.4765,
        "longitude": 153.0166,
        "operator_name": "Evie Networks",
        "usage_type": "Public",
        "usage_cost": "$0.40/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 350, "voltage": 800, "amperage": 500, "quantity": 3},
            {"type": "CHAdeMO", "power_kw": 50, "voltage": 400, "amperage": 125, "quantity": 1},
        ],
    },
    {
        "ocm_id": 100024,
        "name": "JOLT - Newstead",
        "address": "10 Commercial Rd",
        "suburb": "Newstead",
        "state": "QLD",
        "postcode": "4006",
        "country": "Australia",
        "latitude": -27.4553,
        "longitude": 153.0426,
        "operator_name": "JOLT",
        "usage_type": "Public",
        "usage_cost": "Free first 7kWh/day, then $0.35/kWh",
        "is_24hr": 1,
        "status_type": "Operational",
        "connectors": [
            {"type": "Type 2 (Socket)", "power_kw": 7, "voltage": 240, "amperage": 32, "quantity": 6},
        ],
    },
    {
        "ocm_id": 100025,
        "name": "BP Pulse - Chermside",
        "address": "1950 Gympie Rd",
        "suburb": "Chermside",
        "state": "QLD",
        "postcode": "4032",
        "country": "Australia",
        "latitude": -27.3855,
        "longitude": 153.0310,
        "operator_name": "BP Pulse",
        "usage_type": "Public",
        "usage_cost": "$0.45/kWh",
        "is_24hr": 0,
        "status_type": "Operational",
        "connectors": [
            {"type": "CCS (Type 2)", "power_kw": 150, "voltage": 400, "amperage": 375, "quantity": 2},
            {"type": "Type 2 (Socket)", "power_kw": 22, "voltage": 400, "amperage": 32, "quantity": 2},
        ],
    },
]


def seed_stations(db: Session, force: bool = False) -> int:
    count = 0
    if force:
        db.query(Connector).delete()
        db.query(Station).delete()
        db.commit()

    for s in MOCK_STATIONS:
        existing = db.query(Station).filter(Station.ocm_id == s["ocm_id"]).first()
        if existing:
            continue

        import copy
        station_data = copy.deepcopy(s)
        connectors_data = station_data.pop("connectors", [])
        station = Station(**station_data)
        db.add(station)
        db.flush()

        for c in connectors_data:
            db.add(Connector(station_id=station.id, **c))

        count += 1

    db.commit()
    logger.info("Seeded %d mock stations", count)
    return count
